{% set name = "rdata" %}
{% set version = "0.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdata-{{ version }}.tar.gz
  sha256: 86f50312f97569c656f01d6dc343b920ded0ccf884a31decfb670cbef80bab39

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - typing-extensions >4.4
    - numpy
    - pandas
    - python >={{ python_min }},<4.0
    - xarray

test:
  imports:
    - rdata
    - rdata.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vnmabus/rdata
  summary: 'rdata: read R datasets from Python.'
  license: MIT
  license_file: LICENSE
  description: |
    This package parses .rda datasets used in R. It does not depend on the R
    language or its libraries, and thus it is released under a MIT license.
  doc_url: https://rdata.readthedocs.io/
  dev_url: https://github.com/vnmabus/rdata

extra:
  recipe-maintainers:
    - vnmabus
